### ISSUE TITLE
Link to file is broken

### ISSUE THREAD

**Issue by bedrich-schindler** [Vatsim-Scandinavia/controlcenter#598] opened 2023-08-19 14:02 UTC
<img width="746" alt="image" src="https://github.com/Vatsim-Scandinavia/controlcenter/assets/10213870/3609a15b-9a11-48d3-8bb2-926c7fb5f364">

If you open any training report with attached file and you click on the file, file is opened in new tab, but unreadable:

<img width="2056" alt="image" src="https://github.com/Vatsim-Scandinavia/controlcenter/assets/10213870/cdc2f49d-d643-4ce3-a985-32220263275f">

You need to right click on the file and Save file manually.

This behavior is reported by multiple people in Chrome. Firefox and Safari downloads it automatically. `download` attribute may fix the problem

**Comment by blt950** [comment] 2023-08-19 18:17
I'm not able to reproduce this on our production Control Center image. @thor do you by any chance have any ideas here? 
@bedrich-schindler Are you using our provided images and config or did you build and config the installation yourself?

**Comment by bedrich-schindler** [comment] 2023-09-13 09:09
@blt950, we do not use donkerized version on production. I can test it on Dockerized version next week.

**Comment by blt950** [comment] 2023-10-02 10:03
Closing this issue as it has stalled for 3 weeks

**Closed by blt950** 2023-10-02 10:03 UTC
Labels: support
